api_key: ADD_HEAR_API_KEY
home_text: |
    Sputnik Navigation shows prices for many different tokens not only to $, but also to each other!
    
    To program Sputnik Navigation shows only tokens that you want:
    1) Send command /projects —> Bot will send you message with the list of tokens
    2) Reply to this message with the list of tokens that are need to be shown
    3) Enjoy actual prices for interesting pairs in one click!
    
    Sputnik Navigation is an add-on for p2p-exchange @SputnikNetworkBot

projects_text: "Enter the list of interesting projects in the chat, separated by commas. Names like in coingecko.Send 0 to delete the list. Reply to this message. Examples: "
projects_added: |
 Ok. Chat projects added.

help_text: |
    🛰️ Sputnik Navigation 🛰️ is a part of the Sputnik Network - from Community for Community project of the Cosmos Ecosystem
    🛰️ Sputnik Navigation 🛰️ shows the current prices for all pairs, that can be traded at p2p-exchange of the Sputnik Network
    
    🔹 The actual price of tokens is taken from CoinGecko.com
    
    🔹 To receive, send and exchange tokens - use \"Sputnik\" button, or follow the @SputnikNetworkBot
    
    🔹 Video guide \"how to use the Sputnik: youtu.be/NwiI6xXkMcw
    
    🔹 Add 🛰️ Sputnik Navigation 🛰️ to any Telegram-group, and members will have ability to get data on prices of the Cosmos Ecosystem tokens
    
    🔹 If you have any questions, write to technical support: @SputnikNetwork
    
    Main group: @Sputnik_Network
    
    News channel: @SputnikDish
    
    Art channel: @TelescopeART
    
    Web: sputnik.exchange
    
    TW: twitter.com/SputnikNetwork

gas_text: "At what gas price should gwei send you a notification?  Send reply to this message. If you want to specify from-to, send it with a hyphen. For example, 25-35"


tokens: akash-network,band-protocol,binancecoin,bitcanna,bitcoin,bitsong,cerberus-2,certik,chihuahua-token,comdex,cosmos,crypto-com-chain,e-money,e-money-eur,ethereum,fetch-ai,firmachain,ion,iris-network,juno-network,kava,kava-lend,kava-swap,ki,likecoin,lum-network,medibloc,mina-protocol,odin-protocol,osmosis,persistence,regen,rizon,secret,sentinel,sifchain,solana,ssv-network,stargaze,starname,switcheo,terra-luna,terrausd,umee,usdx,velas
image_path: https://dpos.space/cosmos-prices/images/